spring:
  application:
    name: projectservice
  profiles.active: default
---
server:
  port: 8100
---
spring:
  profile: default
  datasource:
      url: jdbc:mysql://localhost:3306/tntproject?tinyInt1isBit=false
      username: root
      password: krishna
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

management:
  security:
    enabled: false
  endpoints.web.exposure.include: health,info,beans,env,refresh,bus-env
server:
  port: 8100
security:
  basic:
    enabled: false
---
spring:
  profile: local

  datasource:
      url: jdbc:mysql://localhost:3306/tntproject?tinyInt1isBit=false
      username: root
      password: krishna
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

management:
  endpoints.web.exposure.include: health,info,beans,env,refresh
server:
  port: 8100
   
---
management:
  endpoints.web.exposure.include: health,info,beans,env,refresh
#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 160000000
#        read-timeout: 160000000
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1